spring:
  cloud:
    gateway:
     discovery:
       # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
       # 默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
       locator:
         enabled: true
         lower-case-service-id: true #使用小写服务名，默认是大写
logging:
  level:
    org.springframework.cloud.gateway: debug